// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmPlanner.Infrastructure.Persistence;

#nullable disable

namespace SmPlanner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SmPlanner.Domain.Clienti.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColoreHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataFineRapporto")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInizioRapporto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoMensile")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NewsletterAlMese")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteEAccordi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Societa")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SponsorizzateAlMese")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti", (string)null);
                });

            modelBuilder.Entity("SmPlanner.Domain.Clienti.Cliente", b =>
                {
                    b.OwnsMany("SmPlanner.Domain.Clienti.PianificazioneGiorno", "Pianificazione", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Giorno")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Post")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Reel")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Storie")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("ClienteId");

                            b1.ToTable("ClientePianificazioneGiorni", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Pianificazione");
                });
#pragma warning restore 612, 618
        }
    }
}
